#!/bin/bash
set -euo pipefail

# ===================================================================
# Objetiva Sync - Deployment Script
# ===================================================================
# Purpose: Automated deployment for Windows/Git Bash and Linux
# Usage: bash deploy.sh
# ===================================================================

# Detect script directory and change to it
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

# Create logs directory if it doesn't exist
mkdir -p logs

# Initialize log file with timestamp
LOG_FILE="logs/deploy-$(date +%Y%m%d-%H%M%S).log"

# Logging function
log() {
  local message="[$(date '+%Y-%m-%d %H:%M:%S')] $*"
  echo "$message" | tee -a "$LOG_FILE"
}

# Error handler
handle_error() {
  local line_num=$1
  log "❌ ERROR: Deployment failed at line $line_num"
  log "Check log file: $LOG_FILE"
  exit 1
}

trap 'handle_error $LINENO' ERR

log "=========================================="
log "Starting Objetiva Sync Deployment"
log "=========================================="
log "Working directory: $SCRIPT_DIR"
log "Log file: $LOG_FILE"
log ""

# ===================================================================
# Pre-flight checks
# ===================================================================

log "📋 Running pre-flight checks..."

# Check Node.js version (require >= 20)
if ! command -v node &> /dev/null; then
  log "❌ Node.js not found. Please install Node.js 20 or higher."
  exit 1
fi

NODE_VERSION=$(node -v | sed 's/v//' | cut -d. -f1)
if [ "$NODE_VERSION" -lt 20 ]; then
  log "❌ Node.js version $NODE_VERSION detected. Required: 20 or higher."
  exit 1
fi
log "✅ Node.js $(node -v) detected"

# Check npm
if ! command -v npm &> /dev/null; then
  log "❌ npm not found. Please install npm."
  exit 1
fi
log "✅ npm $(npm -v) detected"

# Check PM2
if ! command -v pm2 &> /dev/null; then
  log "❌ PM2 not found. Please install with: npm install -g pm2"
  exit 1
fi
log "✅ PM2 $(pm2 -v) detected"

log ""

# ===================================================================
# Load and validate environment variables
# ===================================================================

log "🔍 Loading environment variables..."

# Check .env file exists
if [ ! -f .env ]; then
  log "❌ .env file not found. Please create one based on .env.example"
  exit 1
fi

# Source .env file
set -a
source .env
set +a

log "✅ .env file loaded"
log ""

# Validate required environment variables
log "🔍 Validating required environment variables..."

validate_env_vars() {
  local missing_vars=()

  for var in "$@"; do
    if [ -z "${!var:-}" ]; then
      missing_vars+=("$var")
    fi
  done

  if [ ${#missing_vars[@]} -gt 0 ]; then
    log "❌ Missing required environment variables:"
    for var in "${missing_vars[@]}"; do
      log "   - $var"
    done
    log ""
    log "Please set these variables in .env file"
    exit 1
  fi
}

# Validate required vars (PORT, NODE_ENV, DATABASE_PATH)
# Note: ENCRYPTION_KEY and SESSION_SECRET are auto-generated by the app on first run
validate_env_vars PORT NODE_ENV DATABASE_PATH

log "✅ Required environment variables validated"
log "   PORT: $PORT"
log "   NODE_ENV: $NODE_ENV"
log "   DATABASE_PATH: $DATABASE_PATH"
log ""

# ===================================================================
# Install dependencies
# ===================================================================

log "📦 Installing dependencies..."
npm ci --production=false 2>&1 | tee -a "$LOG_FILE"
log "✅ Dependencies installed"
log ""

# ===================================================================
# Build TypeScript
# ===================================================================

log "🔨 Building TypeScript..."
npm run build 2>&1 | tee -a "$LOG_FILE"

# Verify build output exists
if [ ! -d "dist" ]; then
  log "❌ Build failed: dist/ directory not found"
  exit 1
fi

if [ ! -f "dist/index.js" ]; then
  log "❌ Build failed: dist/index.js not found"
  exit 1
fi

log "✅ TypeScript build completed"
log ""

# ===================================================================
# Ensure database directory exists
# ===================================================================

log "📂 Ensuring database directories exist..."

# Create directory for app runtime database (from DATABASE_PATH env var)
mkdir -p "$(dirname "$DATABASE_PATH")"
log "✅ Created directory for DATABASE_PATH: $(dirname "$DATABASE_PATH")"

# KNOWN COUPLING: drizzle.config.ts hardcodes ./database/objetiva-sync.db path.
# DATABASE_PATH env var is used by the app at runtime, but drizzle-kit reads
# drizzle.config.ts directly and ignores environment variables.
# Both directories must exist to prevent errors.
mkdir -p ./database
log "✅ Created ./database/ directory (required by drizzle.config.ts hardcoded path)"
log ""

# ===================================================================
# Run Drizzle migrations
# ===================================================================

log "🗄️  Running Drizzle migrations..."
npx drizzle-kit migrate 2>&1 | tee -a "$LOG_FILE"
log "✅ Database migrations completed"
log ""

# ===================================================================
# Start/reload PM2 service
# ===================================================================

log "🚀 Starting/reloading PM2 service..."

# Check if process already exists
if pm2 list | grep -q "objetiva-sync"; then
  log "PM2 process 'objetiva-sync' already exists, reloading..."
  pm2 reload ecosystem.config.js --env production 2>&1 | tee -a "$LOG_FILE"
  log "✅ PM2 process reloaded"
else
  log "PM2 process 'objetiva-sync' not found, starting new instance..."
  pm2 start ecosystem.config.js --env production 2>&1 | tee -a "$LOG_FILE"
  log "✅ PM2 process started"
fi

# Save PM2 process list
pm2 save 2>&1 | tee -a "$LOG_FILE"
log "✅ PM2 process list saved"
log ""

# ===================================================================
# Health check
# ===================================================================

log "🏥 Running health check..."
sleep 3

# Check PM2 process status
if pm2 list | grep "objetiva-sync" | grep -q "online"; then
  log "✅ Service is online"
else
  log "⚠️  Service may not be running correctly. Check PM2 logs:"
  log "   pm2 logs objetiva-sync"
  exit 1
fi

log ""
log "=========================================="
log "✅ Sync deployment completed successfully"
log "=========================================="
log ""
log "Service status:"
pm2 list | grep "objetiva-sync" | tee -a "$LOG_FILE"
log ""
log "Useful commands:"
log "  pm2 logs objetiva-sync       - View logs"
log "  pm2 restart objetiva-sync    - Restart service"
log "  pm2 stop objetiva-sync       - Stop service"
log "  pm2 monit                    - Monitor all services"
log ""
log "Dashboard should be available at: http://localhost:$PORT"
log ""
