/**
 * Centralized .env writer with in-memory async mutex.
 *
 * Fixes ENV-04: special characters ($, #, ", \) in values are now always
 * safely double-quoted and escaped, so dotenv reads them back correctly.
 *
 * All writes are serialized through a promise-chain mutex (no external
 * dependencies). After each write, process.env is updated in-place for
 * immediate effect without a service restart.
 */

import * as fs from 'fs/promises'
import * as path from 'path'

// In-memory promise-chain mutex. Serializes all .env writes.
// If doWrite throws, the chain resets to a resolved promise so subsequent
// writes are not permanently blocked.
let writeLock: Promise<void> = Promise.resolve()

/**
 * Escape a value for safe storage inside double-quoted .env entries.
 * - Backslashes must be escaped first (before quote escaping)
 * - Inner double-quotes are escaped as \"
 * - $ and # are safe inside double quotes per dotenv spec
 */
function escapeValue(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

/**
 * Core write implementation. Reads the current .env, replaces or appends
 * a single key=value line, writes back, and updates process.env.
 */
async function doWrite(key: string, value: string): Promise<void> {
  const envPath = path.join(process.cwd(), '.env')
  const escaped = escapeValue(value)
  const line = `${key}="${escaped}"`

  let content: string
  try {
    content = await fs.readFile(envPath, 'utf-8')
  } catch {
    // File does not exist — create with header comment
    content = '# .env — Generated by Objetiva Sync Gateway\n'
  }

  // Use ^KEY= with 'm' flag (multiline) to anchor to line start.
  // This prevents KEY= from matching APP_KEY= or ANOTHER_KEY=.
  const lineRegex = new RegExp(`^${key}=.*$`, 'm')
  if (lineRegex.test(content)) {
    content = content.replace(lineRegex, line)
  } else {
    // Append — ensure there is a trailing newline before the new line
    if (!content.endsWith('\n')) {
      content += '\n'
    }
    content += `${line}\n`
  }

  await fs.writeFile(envPath, content, 'utf-8')

  // Hot-update process.env so the new value is available immediately
  process.env[key] = value
}

/**
 * Write a single environment variable to .env atomically.
 * Concurrent calls are serialized through the in-memory mutex.
 *
 * @param key   Environment variable name (e.g. 'JWT_SECRET')
 * @param value Raw value — will be escaped and double-quoted automatically
 */
export async function writeEnvVar(key: string, value: string): Promise<void> {
  // Attach the write to the end of the chain.
  // The .catch(() => {}) resets the chain on failure so it doesn't poison
  // future writes.
  const write = writeLock.then(() => doWrite(key, value))
  writeLock = write.catch(() => {
    // Reset chain to resolved so subsequent writes can proceed
  })
  return write
}

/**
 * Write multiple environment variables in a single locked batch.
 * All keys are written sequentially under one lock acquisition.
 *
 * @param vars  Record of key→value pairs to write
 */
export async function writeEnvVars(vars: Record<string, string>): Promise<void> {
  const batch = writeLock.then(async () => {
    for (const [key, value] of Object.entries(vars)) {
      await doWrite(key, value)
    }
  })
  writeLock = batch.catch(() => {
    // Reset chain on failure
  })
  return batch
}
